const ICONS = {
    "dialogs": require("../assets/images/icons/dialogs.png"),
    "profile": require("../assets/images/icons/profile.png"),
    "burger": require("../assets/images/icons/burger.png"),
    "avatar": require("../assets/images/avatar.png"),
    "avatar-add": require("../assets/images/avatar-add.png"),
    "avatar-blank": require("../assets/images/icons/avatar-blank.png"),
    "cog": require("../assets/images/icons/cog.png"),
    "add": require("../assets/images/icons/add.png"),
    "exit": require("../assets/images/icons/exit.png"),
    "star-blank": require("../assets/images/icons/star-blank.png"),
    "star-full": require("../assets/images/icons/star-full.png"),
    "star-half": require("../assets/images/icons/star-half.png"),
    "tasks-all": require("../assets/images/icons/tasks-all.png"),
    "tasks-created": require("../assets/images/icons/tasks-created.png"),
    "tasks-create": require("../assets/images/icons/tasks-create.png"),
    "tasks-my": require("../assets/images/icons/tasks-my.png"),
    "share": require("../assets/images/icons/share.png"),
    "filter": require("../assets/images/icons/filter.png"),
    "send": require("../assets/images/icons/send.png"),
    "star": require("../assets/images/icons/created.png"),
    "search": require("../assets/images/icons/search.png"),
    "map": require("../assets/images/icons/map.png"),
    "filter-idle": require("../assets/images/icons/filter_idle.png"),
    "filter-applied": require("../assets/images/icons/filter_applied.png"),
    "notification": require("../assets/images/icons/notification.png"),
    "phone": require("../assets/images/icons/phone.png"),
    "heart": require("../assets/images/icons/like.png"),
    "heart-outline-white": require("../assets/images/icons/like-empty-white.png"),
    "heart-white": require("../assets/images/icons/like-white.png"),
    "settings-gears": require("../assets/images/icons/settings-gears.png"),
    "chevron-right": require("../assets/images/icons/chevron-right.png"),
    "chevron-left": require("../assets/images/icons/chevron-left.png"),
    "information": require("../assets/images/icons/information.png"),
    "translation": require("../assets/images/icons/translation.png"),
    "available": require("../assets/images/icons/available.png"),
    "unavailable": require("../assets/images/icons/unavailable.png"),
    "remove_white": require("../assets/images/icons/remove_white.png"),
    "performers": require("../assets/images/icons/performers.png"),
    "whatsapp": require("../assets/images/icons/whatsapp_logo.png"),
    "call": require("../assets/images/icons/call.png"),
    "profile-user": require("../assets/images/icons/profile-user.png"),
    "done": require("../assets/images/icons/done.png"),
    "more": require("../assets/images/icons/More.png"),
    "square": require("../assets/images/icons/square.png"),
    "check-square": require("../assets/images/icons/check-square.png"),
    "arrow-right": require("../assets/images/icons/arrow-right.png"),
    "arrow-left": require("../assets/images/icons/arrow-left.png"),
    "notification-fill": require("../assets/images/icons/notification-fill-white.png"),
    "notification-disabled": require("../assets/images/icons/notification-disabled.png"),
    "edit": require("../assets/images/icons/edit.png"),
    "radio-button": require("../assets/images/icons/radio-button.png"),
    "radio-button-empty": require("../assets/images/icons/radio-button-empty.png"),
    "megaphone": require("../assets/images/icons/megaphone.png"),
    "trash": require("../assets/images/icons/trash.png"),
    "facebook": require("../assets/images/icons/facebook_icon.png")
};

const icon = name => ICONS[name];

icon.all = Object.keys(ICONS)
    .map(k => ICONS[k]);

export default icon;
